task 3, migrations
dmitryshrv/TestGuru pull request #2
Opened 2022-07-10 11:50 UTC by dmitryshrv

2022-07-10 16:07 UTC, BubuntuClu requested changes

2022-07-10 16:07 UTC, BubuntuClu commented on config/initializers/version.rb
> +    version = '0.1.0'
зачем тебе тут вообще код `version =` ? у тебя метод возвращает строку. присваивать ее перед этим куда-то не имеет смысла

2022-07-10 16:07 UTC, BubuntuClu commented on db/migrate/20220708131159_create_tests.rb
> +      t.integer :category_id
это должен быть внешний ключ, а не просто колонка

2022-07-10 16:07 UTC, BubuntuClu commented on db/migrate/20220708131659_create_questions.rb
> +      t.integer :test_id
это должен быть внешний ключ, а не просто колонка

2022-07-10 16:07 UTC, BubuntuClu commented on db/migrate/20220708131811_create_answers.rb
> +      t.integer :test_id
это должен быть внешний ключ, а не просто колонка

2022-07-11 07:03 UTC, BubuntuClu commented on db/migrate/20220710180748_create_answers.rb
> +      t.references :question, null: false, foreign_key:true
sqlite плохо работает с внешними ключами, потом когда будет переход на потсгрес, ты будешь получать ошибку при создании этого внешнего ключа. ты создаешь сначала таблицу ответов, которая ссылается на таблицу вопросов, которая еще не создана.

нужно порядок создания таблиц поменять

2022-07-11 07:56 UTC, dmitryshrv commented on db/migrate/20220710180748_create_answers.rb
> +      t.references :question, null: false, foreign_key:true
А как это правильно сделать? Дропнуть таблицу и отдельной миграцией её накатить?

2022-07-12 17:57 UTC, merged